Apps/empleados/urls.py
from django.urls import path
from Apps.empleados.views import lista_empleados, editar_empleado, eliminar_empleado, agregar_empleado

app_name='empleados'

urlpatterns= [
    path('lista-empleados',lista_empleados,name='lista_empleados'),
    path('agregar-empleado',agregar_empleado,name='agregar_empleado'),
    path('editar-empleados',editar_empleado, name='editar_empleado'),
    path('eliminar-empleado/<int:id>',eliminar_empleado,name='eliminar_empleado'),

]

Apps/ventas/urls.py
from tkinter.font import names

from django.urls import path
from Apps.ventas.views import (lista_de_categorias, agregar_categoria, eliminar_categoria, editar_categoria,
                               lista_productos, agregar_producto, editar_producto, eliminar_producto, agregar_mayorista,
                               lista_mayoristas, editar_mayorista, eliminar_mayorista,registrar_venta, crear_item_venta,
                               obtener_precio_producto,lista_ventas,imprimir_venta, estadisticas, eliminar_venta)

app_name = 'ventas'

urlpatterns = [

    path('agregar-categoria',agregar_categoria, name='agregar_categoria'),
    path('lista-categorias',lista_de_categorias,name='lista_categorias'),
    path('eliminar-categoria/<int:id>',eliminar_categoria,name='eliminar_categoria'),
    path('editar-categoria',editar_categoria,name='editar_categoria'),
    path('lista-productos',lista_productos,name="lista_productos"),
    path('agregar-producto',agregar_producto,name='agregar_producto'),
    path('editar-producto',editar_producto,name='editar_producto'),
    path('eliminar-producto/<int:id>',eliminar_producto,name='eliminar_producto'),
    path('agregar-mayorista',agregar_mayorista,name='agregar_mayorista'),
    path('lista-mayorista',lista_mayoristas,name='lista_mayoristas'),
    path('editar-mayorista',editar_mayorista,name='editar_mayorista'),
    path('eliminar-mayorista/<int:id>',eliminar_mayorista,name="eliminar_mayorista"),
    path('registrar-venta',registrar_venta,name='registrar_venta'),
    path('crear-item-venta',crear_item_venta,name='crear_item_venta'),
    path('obtener-precio-producto/', obtener_precio_producto, name='obtener_precio_producto'),
    path('lista-ventas',lista_ventas,name='lista_ventas'),
    path('imprimir-venta/<int:id>',imprimir_venta,name='imprimir_venta'),
    path('estadisticas',estadisticas, name='estadisticas'),
    path('elimianar-venta/<int:id>',eliminar_venta,name='eliminar_venta'),

    
]

panaderia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from Apps import empleados

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('ventas/',include('Apps.ventas.urls',namespace='ventas')),
    path('empleados/',include('Apps.empleados.urls',namespace='empleados')),
    path('inventario/',include('Apps.inventario.urls',namespace='inventario')),
    path('',TemplateView.as_view(template_name='base/base.html'),name='home'),
    path('',include('Apps.usuario.urls',namespace='usuario')),
    
]

Apps/ventas/models.py
from django.db import models
from Apps.empleados.models import Empleado



class Categoria(models.Model):
    nombre = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f'{self.nombre}'


class Producto(models.Model):

    descripcion = models.CharField(max_length=100, unique=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad_disponible = models.PositiveIntegerField()
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE,related_name='productos')

    def __str__(self):
        return f'{self.descripcion},{self.cantidad_disponible},{self.categoria}'

    class Meta:
        ordering =['id']


class Venta(models.Model):

    TIPOS_COMPROBANTE =[
        ('factura A','FACTURA A'),
        ('factura B','FACTURA B'),
        ('factura C','FACTURA C'),
        ('factura M','FACTURA M'),
        ('ticket','TICKET'),
        ('recibo A','RECIBO A'),
        ('recibo B','RECIBO B'),
    ]
    TIPOS_VENTA =[
        ('contado','CONTADO'),
        ('debito','DÉBITO'),
        ('credito','CRÉDITO'),
        ('cuotas','CUOTAS'),
    ]
    TIPOS_PAGO=[
        ('tarjeta de credito','TARJETA DE CRÉDITO'),
        ('tarjeta de debito','TARJETA DE DÉBITO'),
        ('contado','CONTADO'),
    ]
    fecha = models.DateField(auto_now=True)
    nro_comprobante = models.CharField(max_length=15 ,unique=True)
    
    comprobante_tipo = models.CharField(max_length=10,choices=TIPOS_COMPROBANTE)
    venta_tipo = models.CharField(max_length=7,choices=TIPOS_VENTA)
    pago_tipo = models.CharField(max_length=18,choices=TIPOS_PAGO)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='ventas_realizadas')
    observaciones = models.TextField(blank=True,null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.fecha} - {self.nro_comprobante} '


class ItemVenta(models.Model):
    venta = models.ForeignKey(Venta,on_delete=models.CASCADE,related_name='items')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    @property
    def subtotal(self):
        return self.producto.precio * self.cantidad

    def __str__(self):
        return f'{self.producto} - cantidad:{self.cantidad}'

    class Meta:
        ordering = ["id"]


class Mayorista(models.Model):

    cuil = models.CharField(max_length=12,unique=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=150)
    rubro = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.nombre},{self.apellido},{self.rubro}'

Apps/ventas/forms.py
from django import forms
from Apps.ventas.models import Categoria, Venta, ItemVenta


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']

        widgets = {
            'nombre': forms.TextInput(attrs={'placeholder': 'nombre de categoria'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control  form-control-sm'


class VentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = ['nro_comprobante', 'comprobante_tipo', 'venta_tipo', 'pago_tipo', 'observaciones']
        widgets = {
            'nro_comprobante': forms.TextInput(attrs={'class':'form-control form-control-sm text-black'}),
            'comprobante_tipo': forms.Select(attrs={'class':'form-select text-black'}),
            'venta_tipo': forms.Select(attrs={'class':'form-select text-black'}),
            'pago_tipo': forms.Select(attrs={'class':'form-select text-black'}),
            'observaciones': forms.Textarea(attrs={'rows': '6', 'cols': '8','class':'form-control form-control-sm text-black'}),
        }


class ItemVentaForm(forms.ModelForm):
    class Meta:
        model = ItemVenta
        fields = ['producto','cantidad']
        widgets = {
                    'producto': forms.Select(attrs={'class':'form-select text-black'}),
                    'cantidad': forms.NumberInput(attrs={'min':'1','value':'1','class':'form-control  form-control-sm'})
                   }

#creamos los formset para la venta

ItemsVentaFormSet = forms.inlineformset_factory(
    Venta,
    ItemVenta,
    form=ItemVentaForm,
    extra=1,
    can_delete=False,
)

Apps/ventas/views.py
from decimal import Decimal
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Count
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import IntegrityError
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from reportlab.pdfgen import canvas
from Apps.ventas.forms import ItemsVentaFormSet, VentaForm
from Apps.ventas.models import Categoria, Producto, Mayorista, Venta, ItemVenta
from ..empleados.models import Empleado


#---------------------------------Categorias----------------------------------------------------------------------



@login_required(login_url='usuario:login')
@permission_required('ventas.view_categoria', raise_exception=True)
def lista_de_categorias(request):
    categorias = Categoria.objects.all()
    return render(request,'ventas/administrarCategorias.html',{'categorias':categorias})



@login_required(login_url='usuario:login')
@permission_required('ventas.add_categoria', raise_exception=True)
def agregar_categoria(request):

    if request.method == 'POST':
        try:
            nombre = request.POST['descripcionProducto']
            nueva_categoria = Categoria(nombre=nombre)
            nueva_categoria.save()

            messages.success(request,f'Categoria "{nombre}" Agregada Exitosamente')

        except IntegrityError:
            messages.error(request,f'La Categoria "{nombre}" ya Existe')

    return redirect(to='ventas:lista_categorias')



@login_required(login_url='usuario:login')
@permission_required('ventas.delete_categoria', raise_exception=True)
def eliminar_categoria(request, id):

        categoria_eliminada = get_object_or_404(Categoria,id=id)
        categoria_eliminada.delete()
        messages.success(request,f'Categoria "{categoria_eliminada.nombre}" Eliminada Exitosamente')

        return redirect(to='ventas:lista_categorias')


@login_required(login_url='usuario:login')
@permission_required('ventas.change_categoria', raise_exception=True)
def editar_categoria(request):

    if request.method == 'POST':
        id = request.POST['categoria_id']
        nuevo_nombre = request.POST['categoria_nombre']
        categoria_modificada = get_object_or_404(Categoria,id=id)
        categoria_modificada.nombre = nuevo_nombre
        categoria_modificada.save()
        messages.success(request,f'Categoria "{nuevo_nombre}" Modificada Exitosamente')

        return redirect(to='ventas:lista_categorias')

#------------------------------------------- PRODUCTOS ---------------------------------------------------------------------------

@login_required(login_url='usuario:login')
@permission_required('ventas.view_producto', raise_exception=True)
def lista_productos(request):
    productos = Producto.objects.all()
    categorias = Categoria.objects.all()
    return render(request,'ventas/administrarProductos.html',{'productos':productos, 'categorias':categorias})

@login_required(login_url='usuario:login')
@permission_required('ventas.add_producto', raise_exception=True)
def agregar_producto(request):

    if request.method == 'POST':
      try:
            id_categoria = request.POST['categoriaProducto']
            categoria = get_object_or_404(Categoria,id =id_categoria)

            descripcion = request.POST['descripcionProducto']
            precio = Decimal(request.POST['precioProducto'])
            cantidad = int(request.POST['cantidadProducto'])

            nuevo_producto = Producto(descripcion=descripcion,precio=precio,cantidad_disponible=cantidad,categoria=categoria)
            nuevo_producto.save()
            messages.success(request, f'Producto "{descripcion}" Registrado Correctamente')

      except ValueError:
          messages.error(request,'Error: valor del precio invalido')
      except IntegrityError:
          messages.error(request,f'El Producto "{descripcion}" ya se encuentra registrado')
      except MultiValueDictKeyError:
          messages.error(request,'Error: Debe Seleccionar o Registrar Previamente una Categoria de Productos')

    return redirect(to='ventas:lista_productos')



@login_required(login_url='usuario:login')
@permission_required('ventas.change_producto', raise_exception=True)

def editar_producto(request):

    if request.method == 'POST':
       try:
            categoria = get_object_or_404(Categoria,id = request.POST['categoriaProductoM'])
            descripcion = request.POST['descripcionProductoM']
            precio = Decimal(request.POST['precioProductoM'])
            cantidad = int(request.POST['cantidadProductoM'])

            producto_actualizado = get_object_or_404(Producto,id=request.POST['id_producto'])
            producto_actualizado.descripcion = descripcion
            producto_actualizado.precio = precio
            producto_actualizado.cantidad_disponible = cantidad
            producto_actualizado.categoria = categoria
            producto_actualizado.save()
            messages.success(request,f'El Producto "{producto_actualizado.descripcion}" se ha Actualizado Correctamente')


       except ValueError:
                messages.error(request,'Error: valor del precio invalido')

    return redirect(to='ventas:lista_productos')


@login_required(login_url='usuario:login')
@permission_required('ventas.delete_producto', raise_exception=True)
def eliminar_producto(request,id):
    producto = get_object_or_404(Producto,id = id)
    producto.delete()
    messages.success(request,f'El Producto "{producto.descripcion}" se ha Eliminado Correctamente')
    return redirect(to='ventas:lista_productos')


#------------------------------------------ MAYORISTAS
@login_required(login_url='usuario:login')
@permission_required('ventas.view_mayorista', raise_exception=True)
def lista_mayoristas(request):

    mayoristas = Mayorista.objects.all()
    return render(request,'ventas/administrarMayoristas.html',{'mayoristas':mayoristas})



@login_required(login_url='usuario:login')
@permission_required('ventas.add_mayorista', raise_exception=True)
def agregar_mayorista(request):

    if request.method == 'POST':
        try:
                cuil = request.POST['cuilMayorista']
                nombre = request.POST['nombreMayorista']
                apellido = request.POST['apellidoMayorista']
                informacion = request.POST['informacionMayorista']
                mayorista = Mayorista(cuil=cuil, nombre=nombre,apellido=apellido, rubro=informacion)
                mayorista.save()
                messages.success(request, f'El Cliente "{nombre}" se ha Registrado Correctamente')

        except IntegrityError:
            messages.error(request,f'El Cliente "{nombre}" ya se Encuentra Registrado')

    return redirect(to='ventas:lista_mayoristas')



@login_required(login_url='usuario:login')
@permission_required('ventas.change_mayorista', raise_exception=True)
def editar_mayorista(request):

    if request.method == 'POST':

        mayorista = get_object_or_404(Mayorista,id = request.POST['id_mayorista'])

        nombre =  request.POST['nombreMayoristaM']
        apellido =  request.POST['apellidoMayoristaM']
        informacion =  request.POST['informacionMayoristaM']
        cuil = request.POST['cuilMayoristaM']

        mayorista.nombre = nombre
        mayorista.apellido = apellido
        mayorista.rubro = informacion
        mayorista.cuil = cuil

        mayorista.save()
        messages.success(request,f'El Cliente "{nombre}" se ha Actualizado Correctamente ')

    return redirect(to='ventas:lista_mayoristas')



@login_required(login_url='usuario:login')
@permission_required('ventas.delete_mayorista', raise_exception=True)
def eliminar_mayorista (request, id):
    mayorista = get_object_or_404(Mayorista,id = id)
    mayorista.delete()
    messages.success(request,f'El Cliente "{mayorista.nombre}" se ha Eliminado Correctamente')
    return redirect(to='ventas:lista_mayoristas')


#------------------------------------------------- VENTAS -----------------------------------------------------------
@login_required(login_url='usuario:login')
@permission_required('ventas.view_venta', raise_exception=True)
def registrar_venta(request):
    categorias = Categoria.objects.all()
    venta_form = VentaForm()
    formset = ItemsVentaFormSet()

    return render(request,'ventas/administrarVentas.html',{'categorias':categorias,'form':venta_form,'formset':formset})


@login_required(login_url='usuario:login')
@permission_required('ventas.add_venta', raise_exception=True)
def crear_item_venta(request):
    if request.method == 'POST':
        form = VentaForm(request.POST)
        formset = ItemsVentaFormSet(request.POST)

        if form.is_valid() and formset.is_valid():
            venta = form.save(commit=False)
            total = 0
            has_stock_error = False  # Variable para verificar si hay errores de stock

            for item_form in formset:
                producto = item_form.cleaned_data.get('producto')
                cantidad = item_form.cleaned_data.get('cantidad')

                if producto and cantidad:
                    # Comprobamos si hay suficiente stock
                    if producto.cantidad_disponible < cantidad:
                        item_form.add_error('cantidad',f'Solo hay {producto.cantidad_disponible} unidades disponibles de {producto.descripcion}.')
                        has_stock_error = True
                    else:
                        total += producto.precio * cantidad

            if has_stock_error:
                messages.error(request, 'Error: No se puede completar la venta debido a falta de stock.')
            else:
                # Guardamos los cambios si no hay errores de stock
                venta.total = total

                #obtenemos al empleado
                usuario = request.user

Apps/ventas/templates/ventas/administrarCategorias.html
{% extends "base/base.html" %}
{% block title %} Categorias {% endblock %}
{% block contenido %}



        <!-- contenido -->
            <div class="card p-3" style="border-radius: 10px;">
              <p class="card-title">Administración de Categorias</p>

                <form action="{% url 'ventas:agregar_categoria' %}" method="POST" class="formularioRegistrarProducto mb-4 ">
                  {% csrf_token %}
                    <div class="row">
                      <div class="col-md-4 me-2">
                          <div class="form-group">
                              <label for="descripcionProducto">Descripcion:</label>
                              <input type="text" class="form-control  form-control-sm " id="descripcionProducto" name="descripcionProducto" placeholder="nombre de categoria" required >
                          </div>

                      </div>

                        <div class="col-md-6 me-2">
                 {% if messages %}

                     {% for message in messages %}

                         {% if 'success' in message.tags %}
                            <div  class=" alert alert-success d-flex align-items-center" role="alert">
                                 <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                                    <div>
                                                {{message}}
                                    </div>
                            </div>
                            {% elif 'error' in message.tags %}
                            <div class="alert alert-danger d-flex align-items-center" role="alert">
                                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                                    <div>
                                                {{message}}
                                    </div>
                            </div>
                         {% endif %}

                     {% endfor %}

                 {% endif %}
                         </div>
                  </div>

                  <button type="submit" class="btn btn-success btn-sm me-2">registrar</button>
                  <button type="reset" class="btn btn-danger btn-sm">cancelar</button>    
              </form>
  
        <!--Tabla para editar o eliminar una categoria-->
        
        <div class="col-md-4 mt-4">
          <div class="form-group">
            <i class="icon-magnifier"></i>
              <label for="buscarProducto">Buscar:</label>
              <input type="text" class="form-control  form-control-sm " id="buscarProducto" name="buscarProducto" placeholder="nombre de categoria" required oninput="filtrarTablaCategorias()" >
          </div>
        </div>
        <div class="col-md-6">    
        <div class="table-responsive mt-1 mb-4" style="max-height: 400px; overflow-y: auto;">
          <table class="table table-hover mb-4" id="tablaContenido" >
            <thead>
              <tr>
                <th><strong>Codigo</strong></th>
                <th><strong>Descripcion</strong></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for categoria in categorias %}
              <tr>
                <td>{{categoria.id}}</td>
                <td>{{categoria.nombre}}</td>
                <td><button type="button" class="btn btn-warning btn-sm me-2" onclick="modalEditarCategoria('{{ categoria.id }}', '{{ categoria.nombre }}')">editar</button>   <button class="btn btn-danger btn-sm" onclick="modalEliminarCategoria('{{ categoria.id }}')">eliminar</button> </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        </div>
          </div>

            <!-- Modal de Bootstrap para editar una categoria -->
<div class="modal fade" id="modalEditarCategoria" tabindex="-1" aria-labelledby="modalEditarCategoriaLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalEditarCategoriaLabel">Editar Categoría</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" style="background-color: #1C1B29">
        <form id="formEditarCategoria" method="POST" action="{% url 'ventas:editar_categoria' %}">
          {% csrf_token %}
          <input type="hidden" id="categoriaId" name="categoria_id"> <!-- Campo oculto para el ID -->

          <div class="mb-3">
            <label for="categoriaNombre" class="form-label form-control-sm " style="color: #32CD32">Nombre de la Categoría</label>
            <input type="text" class="form-control  form-control-sm  " id="categoriaNombre" name="categoria_nombre" style="background-color:white">
          </div>

          <button type="submit" class="btn btn-primary btn-sm">Guardar cambios</button>
          <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal" aria-label="Close">cancelar</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- modal para eliminar una categoria-->
<div class="modal fade" id="modalEliminar" tabindex="-1" aria-labelledby="modalEliminar" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="modal">Eliminar</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body text-center" style="background-color: #1C1B29">
              <label for="confirmarEliminar" class="form-label form-control-sm" style="color: #32CD32">¿Está seguro?</label><br>
              <a id="confirmarEliminar" class="btn btn-danger btn-sm mt-3 me-2" href="#">Eliminar</a>
              <button type="button" class="btn btn-danger btn-sm mt-3" data-bs-dismiss="modal" aria-label="Close">cancelar</button>
          </div>
      </div>
  </div>
</div>

        {% endblock %}

Apps/ventas/templates/ventas/estadisticas.html
{% extends "base/base.html" %}
{% block title %} Estadisticas de Ventas {% endblock %}
{% block contenido %}


<!-- contenido -->
    <div class="card p-3" style="border-radius: 10px;">
        <p class="card-title mb-4">Estadisticas</p>

        <!--Tabla de estadisticas -->
        <p><strong>Empleado con mas Ventas</strong></p>

        <div class="col-md-4 mt-4">
          <div class="form-group">
            <i class="icon-magnifier"></i>
              <label for="buscarEmpleado">Buscar:</label>
              <input type="text" class="form-control  form-control-sm " id="buscarEmpleado"  placeholder="nombre de empleado" required oninput="filtrarTablaEmpleados()" >
          </div>
        </div>

        <div class="col-md-6">
            <div class="table-responsive mt-1 mb-4" style="max-height: 400px; overflow-y: auto;">
              <table class="table table-hover mb-4" id="tablaEmpleados" >
                <thead>
                      <tr>
                        <th>Cuil</th>
                        <th><strong>Empleado</strong></th>
                        <th><strong>Nro de Ventas</strong></th>

                      </tr>
                </thead>
                    <tbody>
                            {% for empleado in empleados %}
                          <tr>
                                <td>{{empleado.cuil}}</td>
                                <td><a href="{% url 'empleados:lista_empleados' %}">{{empleado}}</a></td>
                                <td>{{empleado.nro_ventas}}</td>
                          </tr>
                            {% endfor %}
                    </tbody>
              </table>
            </div>
        </div>
   </div>














{% endblock %}

Apps/ventas/templates/ventas/ventasRealizadas.html
{% extends "base/base.html" %}
{% block title %} Lista de Ventas {% endblock %}
{% block contenido %}
{% load static %}


<div class="card p-3" style="border-radius: 10px;">
              <p class="card-title">Lista de Ventas</p>

    <div class="col-md-6 me-2">
                            {% if messages %}

                                {% for message in messages %}

                                    {% if 'success' in message.tags %}
                                       <div  class=" alert alert-success d-flex align-items-center" role="alert">
                                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                                               <div>
                                                           {{message}}
                                               </div>
                                       </div>
                                       {% elif 'error' in message.tags %}
                                       <div class="alert alert-danger d-flex align-items-center" role="alert">
                                           <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                                               <div>
                                                           {{message}}
                                               </div>
                                       </div>
                                    {% endif %}

                                {% endfor %}

                            {% endif %}
   </div>



    <div class="col-md-12">

        <!--Tabla de listado de ventas-->
        <div class="col-md-10">
        <div class="table-responsive mt-1 mb-4" style="max-height: 400px; overflow-y: auto;">
          <table class="table table-hover mb-4" id="tablaContenido" >
            <thead>
              <tr>
                <th><strong>Nro Comprobante</strong></th>
                <th><strong>Fecha</strong></th>
                <th><strong>Total</strong></th>
                <th><strong>Empleado</strong></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                {% for venta in ventas %}
              <tr>
                <td>{{venta.nro_comprobante}}</td>
                <td>{{venta.fecha|date:"d/m/y"}}</td>
                <td>{{venta.total}}</td>
                <td>{{venta.empleado}}</td>
                  <td>  <a class="me-4"  href="{% url 'ventas:imprimir_venta' venta.id %}"> <img src="{% static 'assets/icons/descarga.png' %}"> </a> {% if user.is_superuser == True %} <a class="btn btn-danger btn-sm" href="{% url 'ventas:eliminar_venta' venta.id %}">eliminar</a>{% endif %}  </td>
              </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
        </div>
  </div>



</div>



{% endblock %}