Apps/inventario/urls.py
from tkinter.font import names

from django.urls import path
from Apps.inventario.views import (lista_proveedores, agregar_proveedor, editar_proveedor, eliminar_proveedor,
                                   lista_stock, agregar_insumo, eliminar_proveedor_insumo, editar_proveedor_insumo, editar_insumo,
                                   eliminar_insumo,registrar_pedido, obtener_insumos_proveedor,crear_item_pedido, lista_pedidos,detalles_pedido,
                                   crear_item_pedido_recibido,todos_los_pedidos,eliminar_pedido,detalles_pedido_recibido,eliminar_pedido_recibido)

app_name='inventario'

urlpatterns = [
    path('lista-proveedores',lista_proveedores,name='lista_proveedores'),
    path('agregar-proveedor',agregar_proveedor,name='agregar_proveedor'),
    path('editar-proveedor',editar_proveedor,name='editar_proveedor'),
    path('eliminar-proveedor/<int:id>',eliminar_proveedor,name='eliminar_proveedor'),
    path('lista-stock',lista_stock,name='stock_disponible'),
    path('agregar-insumo',agregar_insumo,name='agregar_insumo'),
    path('editar-proveedor-insumo/<int:id>',editar_proveedor_insumo,name='editar_proveedor_insumo'),
    path('elimianr-proveedor-insumo/<int:id>',eliminar_proveedor_insumo,name='eliminar_proveedor_insumo'),
    path('editar-insumo',editar_insumo,name='editar_insumo'),
    path('eliminar-insumo/<int:id>',eliminar_insumo,name='eliminar_insumo'),
    path('registrar-pedido',registrar_pedido,name='registrar_pedido'),
    path('obtener-insumos-proveedor/<int:id>',obtener_insumos_proveedor,name='obtener_insumos_proveedor'),
    path('crear-item-pedido',crear_item_pedido,name='crear_item_pedido'),
    path('lista-pedidos',lista_pedidos,name='lista_pedidos'),
    path('detalles-pedido/<int:id>',detalles_pedido,name='detalles_pedido'),
    path('crear-item-pedido-recibido',crear_item_pedido_recibido,name='crear_item_pedido_recibido'),
    path('todos-los-pedidos',todos_los_pedidos,name='todos_los_pedidos'),
    path('eliminar-pedido/<int:id>',eliminar_pedido,name='eliminar_pedido'),
    path('detalles-pedidos-recibidos/<int:id>',detalles_pedido_recibido,name='detalles_pedido_recibido'),
    path('eliminar-pedido-recibido/<int:id>',eliminar_pedido_recibido,name='eliminar_pedido_recibido'),


]

panaderia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from Apps import empleados

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('ventas/',include('Apps.ventas.urls',namespace='ventas')),
    path('empleados/',include('Apps.empleados.urls',namespace='empleados')),
    path('inventario/',include('Apps.inventario.urls',namespace='inventario')),
    path('',TemplateView.as_view(template_name='base/base.html'),name='home'),
    path('',include('Apps.usuario.urls',namespace='usuario')),
    
]

Apps/inventario/models.py
from django.db import models
from Apps.empleados.models import Empleado


class Proveedor(models.Model):

    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=150)
    empresa = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.nombre} - {self.apellido} - {self.empresa}'

    class Meta:
        ordering = ['id']


class Insumo (models.Model):

    nombre = models.CharField(max_length=100)
    proveedores = models.ManyToManyField(Proveedor,related_name='insumos')
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.nombre},{self.cantidad}'

    class Meta:
        ordering = ['id']


class Pedido (models.Model):
    estado = models.BooleanField(default=False)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='pedidos_realizados')
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    nro_pedido = models.CharField(max_length=15, unique=True)
    fecha = models.DateField(auto_now_add=True)
    observaciones =  models.CharField(blank=True, null=True)


    def __str__(self):
        return f'{self.nro_pedido},{self.fecha}'

    class Meta:
        ordering = ['id']


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name='items')
    insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()



class PedidoRecibido (models.Model):

    fecha = models.DateField(auto_now_add=True)
    nro_comprobante = models.CharField(max_length=15, unique=True)
    nro_pedido = models.CharField(max_length=15,unique=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    conformidad = models.BooleanField(default=True)
    observaciones = models.TextField(blank=True,null=True)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='pedidos_recibidos')
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nro_comprobante},{self.fecha},{self.proveedor}'

    class Meta:
        ordering = ['id']


class ItemPedidoRecicido(models.Model):
    pedido_recibido = models.ForeignKey(PedidoRecibido, on_delete=models.CASCADE,related_name='items')
    insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unit = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)

Apps/inventario/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.db.models.fields import return_None
from django.db.transaction import commit
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages


from Apps.inventario.forms import ProveedorForm, ItemsPedidosFormSet, ItemsPedidosRecibidoFormSet
from Apps.inventario.models import Proveedor, Insumo, Pedido, ItemPedido, PedidoRecibido, ItemPedidoRecicido
from Apps.ventas.forms import ItemsVentaFormSet
from Apps.ventas.models import Categoria
from Apps.empleados.models import Empleado



#--------------------------------------------- PROVEEDOR ---------------------------------------------------------------------------------
@login_required(login_url='usuario:login')
@permission_required('inventario.view_proveedor', raise_exception=True)
def lista_proveedores(request):
    proveedores = Proveedor.objects.all()
    proveedor_form = ProveedorForm()
    return render(request, 'inventario/administrarProveedores.html',{'form':proveedor_form ,'proveedores':proveedores})



@login_required(login_url='usuario:login')
@permission_required('inventario.add_proveedor', raise_exception=True)
def agregar_proveedor(request):
    if request.method == 'POST':
        proveedor_form = ProveedorForm(request.POST)
        if proveedor_form.is_valid():
            proveedor_form.save()
            messages.success(request,f'Proveedor "{proveedor_form.cleaned_data['nombre']}" Registrado Correctamente')
            return redirect(to='inventario:lista_proveedores')
        else:
            # Si el formulario no es válido, renderiza la página con los errores
            return render(request, 'inventario/administrarProveedores.html', {
                'form': proveedor_form,
                'errors': proveedor_form.errors
            })



@login_required(login_url='usuario:login')
@permission_required('inventario.change_proveedor', raise_exception=True)
def editar_proveedor(request):
    if request.method == 'POST':
        proveedor = get_object_or_404(Proveedor, id = request.POST['id_proveedor'])
        proveedor.nombre = request.POST['nombreProveedorM']
        proveedor.apellido = request.POST['apellidoProveedorM']
        proveedor.empresa = request.POST['empresaM']

        proveedor.save()
        messages.success(request,f'Proveedor "{proveedor.nombre}" Actualizado Correctamente')
        return redirect(to='inventario:lista_proveedores')



@login_required(login_url='usuario:login')
@permission_required('inventario.delete_proveedor', raise_exception=True)
def eliminar_proveedor(request, id):
    proveedor = get_object_or_404(Proveedor, id=id)
    proveedor.delete()
    messages.success(request,f'Proveedor "{proveedor.nombre}" Eliminado Exitosamente')
    return  redirect(to='inventario:lista_proveedores')

#---------------------------------------INSUMOS------------------------------------------------------------------
@login_required(login_url='usuario:login')
@permission_required('inventario.view_insumo', raise_exception=True)
def lista_stock(request):
    stock = Insumo.objects.all()
    proveedores = Proveedor.objects.all()
    return render(request,'inventario/administrarStock.html',{'stock':stock,'proveedores':proveedores})

@login_required(login_url='usuario:login')
@permission_required('inventario.add_insumo', raise_exception=True)
def agregar_insumo(request):

    if request.method == 'POST':
          try:
                nombre = request.POST['descripcion']
                cantidad = int(request.POST['cantidad'])
                nuevo_insumo = Insumo(nombre=nombre,cantidad=cantidad)
                nuevo_insumo.save()

                proveedores_id =request.POST.getlist('proveedores')
                proveedores = Proveedor.objects.filter(id__in=proveedores_id)
                nuevo_insumo.proveedores.set(proveedores)

                messages.success(request,f'Insumo {nombre} Registrado Correctamente')

          except ValueError:
              messages.error(request, 'Error: vala de cantidad invalido')

    return redirect(to='inventario:stock_disponible')



@login_required(login_url='usuario:login')
@permission_required('inventario.change_insumo', raise_exception=True)
def editar_proveedor_insumo(request,id):
    if request.method == 'POST':
        insumo = get_object_or_404(Insumo, id = id)
        nuevo_proveedor_id = request.POST.get('nuevo_proveedor')

        if nuevo_proveedor_id:
            nuevo_proveedor = get_object_or_404(Proveedor, id=nuevo_proveedor_id)
            insumo.proveedores.add(nuevo_proveedor)
            messages.success(request,'Proveedor Asignado Correctamente')
        return redirect(to='inventario:stock_disponible')


@login_required(login_url='usuario:login')
@permission_required('inventario.delete_insumo', raise_exception=True)
def eliminar_proveedor_insumo(request,id):
        if request.method == 'POST':
            insumo = get_object_or_404(Insumo, id = id)
            proveedor_a_eliminar_id = request.POST.get('proveedor_a_eliminar')

            if proveedor_a_eliminar_id:
                proveedor_a_eliminar = get_object_or_404(Proveedor, id=proveedor_a_eliminar_id)
                insumo.proveedores.remove(proveedor_a_eliminar)
                messages.success(request,f'Proveedor "{proveedor_a_eliminar.nombre}" Eliminado Correctamente')
            return redirect('inventario:stock_disponible')

@login_required(login_url='usuario:login')
@permission_required('inventario.change_insumo', raise_exception=True)
def editar_insumo(request):
    if request.method == 'POST':
        id_insumo = request.POST['id_insumo']
        insumo = get_object_or_404(Insumo,id = id_insumo)
        nombre = request.POST['descripcionM']
        cantidad = int(request.POST['cantidadM'])

        insumo.nombre=nombre
        insumo.cantidad=cantidad

        insumo.save()
        messages.success(request,f'Insumo "{nombre}" Actualizado Correctamente')

        return redirect(to='inventario:stock_disponible')

@login_required(login_url='usuario:login')
@permission_required('inventario.delete_insumo', raise_exception=True)
def eliminar_insumo(request,id):
    insumo = get_object_or_404(Insumo, id=id)
    if insumo:
        insumo.delete()
        messages.success(request,f'Insumo "{insumo.nombre}" Eliminado Correctamente')
    else:
        messages.error(request,f'Error: No se Pudo Eliminar Insumo 2{insumo.nombre}"')

    return redirect(to='inventario:stock_disponible')

#---------------------------------------- Pedidos--------------------------------------------------------------------
@login_required(login_url='usuario:login')
@permission_required('inventario.view_pedido', raise_exception=True)
def registrar_pedido(request):
    proveedores = Proveedor.objects.all()
    formset = ItemsPedidosFormSet()
    return render(request,'inventario/realizarPedido.html',{'proveedores':proveedores,'formset':formset})



def obtener_insumos_proveedor(request,id):
    if request.method == 'GET':
        get_object_or_404(Proveedor,id=id)
        insumos = Insumo.objects.filter(proveedores__id = id).values('id','nombre','cantidad')

    return JsonResponse(list(insumos), safe=False)


from django.contrib import messages

@login_required(login_url='usuario:login')
@permission_required('inventario.add_pedido', raise_exception=True)
@permission_required('inventario.add_itempedido', raise_exception=True)
def crear_item_pedido(request):
    if request.method == 'POST':
        # Obtenemos el ID del proveedor desde el formulario
        proveedor_id = request.POST['proveedor-select']
        nro_pedido = request.POST['nro_pedido']
        observaciones = request.POST['observaciones']

        # Obtenemos la instancia de Proveedor
        proveedor = Proveedor.objects.get(id=proveedor_id)

        # Obtenemos el usuario actual y luego el empleado asociado
        usuario = request.user
        empleado = Empleado.objects.get(usuario=usuario)

        # Creamos el pedido con los datos obtenidos
        nuevo_pedido = Pedido(
            nro_pedido=nro_pedido,
            observaciones=observaciones,
            proveedor=proveedor,
            empleado=empleado
        )
        nuevo_pedido.save()

        # Inicializamos el formset con los datos POST
        formset = ItemsPedidosFormSet(request.POST, instance=nuevo_pedido)

        # Validamos el formset antes de acceder a los datos limpios
        if formset.is_valid():
            has_error = False  # Variable para rastrear errores

            for item_form in formset:
                insumo = item_form.cleaned_data.get('insumo')
                cantidad = item_form.cleaned_data.get('cantidad')

                # Verificamos si la cantidad es 0 y añadimos un error específico
                if insumo and cantidad is not None:
                    if cantidad == 0:
                        item_form.add_error('cantidad', 'La cantidad no puede ser 0.')
                        has_error = True
                    else:
                        # Guarda cada item del formset con el pedido asociado
                        item = item_form.save(commit=False)
                        item.pedido = nuevo_pedido
                        item.save()

                        # Actualizamos la cantidad de cada insumo (es un insumo, no deberia actualizar el stock)
                        #insumo.cantidad += cantidad
                        #insumo.save()

            # Si no hay errores específicos, guardamos el pedido
            if not has_error:

                messages.success(request, f'Pedido Nro: "{nro_pedido}" Registrado Correctamente')
                return redirect(to='inventario:registrar_pedido')
            else:
                messages.error(request, 'Error: La cantidad no puede ser Cero.')

        else:

Apps/inventario/templates/inventario/administrarStock.html
{% extends 'base/base.html' %}
{%block title%} Administracion de Stock {% endblock %}
{% block contenido %}


<div class="card p-3" style="border-radius: 10px;">
              <p class="card-title">Administración de Stock</p>
                <form class="formularioRegistrarInsumo mb-4 " action="{% url 'inventario:agregar_insumo' %}" method="POST">
                    {%csrf_token%}
                  <div class="row">

                          <div class="col-md-4 me-2">
                              <div class="form-group">
                                  <label>Descripcion:</label>
                                  <input type="text" id="descripcion" name="descripcion" class="form-control form-control-sm" placeholder="descripcion o nombre del insumo">

                              </div>
                          </div>
                          <div class="col-md-1 me-2">
                              <div class="form-group">
                                <label>Cantidad:</label>
                                  <input type="number" id="cantidad" name="cantidad" class="form-control form-control-sm" min="0" value="1">

                              </div>
                          </div>

                      </div>

                      

                  <button type="submit" class="btn btn-success btn-sm me-2">registrar</button>
                  <button type="reset" class="btn btn-danger btn-sm">cancelar</button>
              </form>

             <div class="col-md-6 me-2">
                 {% if messages %}

                     {% for message in messages %}

                         {% if 'success' in message.tags %}
                            <div  class=" alert alert-success d-flex align-items-center" role="alert">
                                 <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                                    <div>
                                                {{message}}
                                    </div>
                            </div>
                            {% elif 'error' in message.tags %}
                            <div class="alert alert-danger d-flex align-items-center" role="alert">
                                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                                    <div>
                                                {{message}}
                                    </div>
                            </div>
                         {% endif %}

                     {% endfor %}

                 {% endif %}
                </div>

                 <!--Tabla para editar o eliminar un Insumo-->

        <div class="col-md-4 mt-4">
          <div class="form-group">
            <i class="icon-magnifier"></i>
              <label for="buscarInsumo">Buscar:</label>
              <input type="text" class="form-control form-control-sm " id="buscarInsumo"  placeholder="Insumo" required oninput="filtrarTablaInsumos()">
          </div>
        </div>
              <div class="table-responsive mt-1 mb-3 col-md-12" style="max-height: 400px; overflow-y: auto;">
                <table class="table table-hover mb-4" id="tablaInsumos">
                  <thead>
                    <tr>
                      <th><strong>Descripcion</strong></th>
                      <th><strong>Cantidad</strong></th>
                      <th><strong>Proveedor</strong></th>
                      <th><strong>Asignar Proveedor</strong></th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>

                        {% for insumo in stock %}
                    <tr>
                      <td>{{insumo.nombre}}</td>
                      <td>{{insumo.cantidad}}</td>
                      <td>
                            <select class="form-control form-control-sm text-black" >
                                {% for proveedor in insumo.proveedores.all %}
                                    <option>{{ proveedor.nombre }} - ({{ proveedor.empresa }})</option>
                                {% empty %}
                                    <option>Sin proveedores asignados</option>
                                {% endfor %}
                            </select>
                      </td>
                      <td>
                             <div class="d-flex align-items-center">
                        <!-- Formulario para asignar un nuevo proveedor -->
                        <form action="{% url 'inventario:editar_proveedor_insumo' insumo.id %}" method="POST" class="d-inline-block me-2">
                            {% csrf_token %}
                            <select name="nuevo_proveedor" class="form-control form-control-sm mb-1 text-black">
                                <option value="">Seleccionar proveedor</option>
                                {% for proveedor in proveedores %}
                                    <option value="{{ proveedor.id }}">{{ proveedor.nombre }} - {{ proveedor.empresa }}</option>
                                {% endfor %}
                            </select>
                            <button type="submit" class="btn btn-primary btn-sm ms-1">Asignar</button>
                        </form>
                             </div>
                      </td>
                        <td>
                        <!-- Formulario para eliminar un proveedor asignado -->
                        <form action="{% url 'inventario:eliminar_proveedor_insumo' insumo.id %}" method="POST" class="d-inline-block">
                            {% csrf_token %}
                            <select name="proveedor_a_eliminar" class="form-control form-control-sm mb-1 text-black">
                                {% for proveedor in insumo.proveedores.all %}
                                    <option value="{{ proveedor.id }}">{{ proveedor.nombre }} - {{ proveedor.empresa }}</option>
                                {% empty %}
                                    <option>No hay proveedores asignados</option>
                                {% endfor %}
                            </select>
                            <button type="submit" class="btn btn-danger btn-sm ms-1">Eliminar Proveedor</button>
                        </form>

                </td>
                        <td> <button class="btn btn-warning btn-sm" onclick="modalEditarInsumo({{insumo.id}},'{{insumo.nombre}}','{{insumo.cantidad}}')">editar</button>
                             <button class="btn btn-danger btn-sm " onclick="modalEliminarInsumo({{insumo.id}})">eliminar</button>
                        </td>

                    </tr>
                            {% endfor %}

                  </tbody>
                </table>
              </div>

<!-- Modal para Editar un Insumo-->
<div class="modal fade" id="modalEditarInsumo" tabindex="-1" aria-labelledby="modalEditarInsumoLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalEditarInsumoLabel">Editar Insumo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" style="background-color: #1C1B29">
        <form id="formEditarInsumo" action="{% url 'inventario:editar_insumo' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" id="id_insumo" name="id_insumo">

          <div class="mb-3">
            <label style="color: #32CD32">Descripcion:</label>
            <input type="text" id="descripcionM" name="descripcionM" class="form-control form-control-sm text-white">
          </div>

          <div class="col-md-2 mb-3">
            <label style="color: #32CD32">Cantidad:</label>
            <input type="number" id="cantidadM" name="cantidadM" class="form-control form-control-sm text-white" min="0" value="1">
          </div>

          <button type="submit" class="btn btn-success btn-sm me-2">Guardar cambios</button>
          <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
        </form>
      </div>
    </div>
  </div>
</div>
        <!-- modal para eliminar un Insumo -->
    <div class="modal fade" id="modalEliminar" tabindex="-1" aria-labelledby="modalEliminar" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="modal">Eliminar</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body text-center" style="background-color: #1C1B29">
              <label for="confirmarEliminar" class="form-label form-control-sm" style="color: #32CD32">¿Está seguro?</label><br>
              <a id="confirmarEliminar" class="btn btn-danger btn-sm mt-3 me-2" href="#">Eliminar</a>
              <button type="button" class="btn btn-danger btn-sm mt-3" data-bs-dismiss="modal" aria-label="Close">cancelar</button>
          </div>
      </div>
  </div>
</div>

</div>


{% endblock %}